name: snake

on:
  schedule:
    # 11:30 PM IST = 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Snake Files
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: progharshith
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Create contribution commit
        run: |
          mkdir -p .github
          echo "Last update: $(date -u)" > .github/contribution-log.txt

      - name: Commit contribution file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .github/contribution-log.txt

          git commit -m "chore: daily contribution update" || exit 0

      - name: Push contribution commit
        run: |
          git push origin master

      - name: Publish snake files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
