name: Generate Snake

on:
  schedule:
    - cron: "0 18 * * *" # 11:30 PM IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: progharshith
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=00FF9C&color_dots=#000000,#001a12,#003d2b,#00FF9C,#7CFFCB

      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist"
          message: "Generate contribution snake"
